services:
  node-app:
    build:
      context: ./
      dockerfile: docker/nodeJs/Dockerfile
    container_name: node-app
    volumes:
      - ./api:/home/node/app/api
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    env_file:
      - .env

  mysql-db:
    build:
      context: ./
      dockerfile: docker/sql/Dockerfile
    container_name: mysql-db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db

volumes:
  mysql_data:
